import L from 'leaflet';
import './style.css';
import {dayRange,localDate,localInput,localToUtc} from './time';
import {limits,type Point} from './model';
import type {Section} from './track';
import {telemetry} from './telemetry';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const worker=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});let seq=0;const pending=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void}>();
worker.onmessage=({data})=>{if(data.type==='progress'){$('status').textContent=data.message;return;}const p=pending.get(data.id);if(!p)return;pending.delete(data.id);if(data.type==='error')p.reject(new Error(data.message));else p.resolve(data);};
worker.onerror=()=>{for(const p of pending.values())p.reject(new Error('Local processing worker stopped. Clear the sources and try smaller files.'));pending.clear();};
function request(data:any):Promise<any>{return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});worker.postMessage({...data,id});});}
const sources:{id:string;name:string;format:string;count:number;start:number;end:number}[]=[];
const zone=$<HTMLSelectElement>('zone');const zones=[...new Set([Intl.DateTimeFormat().resolvedOptions().timeZone,'UTC',...Intl.supportedValuesOf('timeZone')])];zone.innerHTML=zones.map(z=>`<option>${escape(z)}</option>`).join('');
const map=L.map('map',{preferCanvas:true}).setView([30,0],2);const tracks=L.layerGroup().addTo(map);let tileLayer:L.TileLayer|undefined,highlight:L.CircleMarker|undefined,current:any;let busy=false,renderGeneration=0;
const colors:Record<string,string>={recorded:'#286753',good:'#518dc5',uncertain:'#c79736',gap:'#a5a69c'};
function status(text:string,error=false){$('status').textContent=text;$('status').className=error?'error':'notice';}
function formatTime(time:number){return new Intl.DateTimeFormat(undefined,{timeZone:zone.value,dateStyle:'medium',timeStyle:'medium'}).format(time);}
function metadata(p:Point){return `${formatTime(p.time)} · ${p.lat.toFixed(6)}, ${p.lon.toFixed(6)} · ${p.source} · ${p.generated?'Interpolated':'Original'} · ${p.confidence}${p.accuracy!=null?' · accuracy '+p.accuracy+' m':''}`;}
function selectPoint(p:Point){highlight?.remove();highlight=L.circleMarker([p.lat,p.lon],{radius:9,color:'#273d2a',weight:3,fillColor:'#fff',fillOpacity:1}).addTo(map);$('metadata').textContent=metadata(p);$('selection').textContent=new Date(p.time).toLocaleTimeString(undefined,{timeZone:zone.value});}
$('tiles').onchange=()=>{if($<HTMLInputElement>('tiles').checked){tileLayer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);}else{tileLayer?.remove();tileLayer=undefined;}};
map.on('click',e=>{if(!current?.points.length)return;const ps=current.points as Point[];const p=ps.reduce((a,b)=>map.latLngToLayerPoint([a.lat,a.lon]).distanceTo(map.latLngToLayerPoint(e.latlng))<map.latLngToLayerPoint([b.lat,b.lon]).distanceTo(map.latLngToLayerPoint(e.latlng))?a:b);selectPoint(p);});
function list(){ $('sources').innerHTML=sources.map(s=>`<div class="source"><button data-remove="${s.id}" aria-label="Remove ${escape(s.name)}">×</button><strong>${escape(s.name)}</strong><small>${escape(s.format)} · ${s.count.toLocaleString()} GPS records</small></div>`).join('');$('settings').hidden=!sources.length;$('clear').hidden=!sources.length;$('hero').classList.toggle('loaded',!!sources.length);document.querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.onclick=async()=>{if(busy)return;await request({type:'remove',fileId:b.dataset.remove});const i=sources.findIndex(s=>s.id===b.dataset.remove);sources.splice(i,1);list();if(sources.length){setDays();await render();}else resetView();});}
function setDays(){if(!sources.length)return;const start=Math.min(...sources.map(s=>s.start)),end=Math.max(...sources.map(s=>s.end));const days=new Set<string>();for(let t=start;t<=end;t+=12*3600000){days.add(localDate(t,zone.value));if(days.size>20000)throw new Error('Track spans more than 20,000 days. Use a smaller date range.');}days.add(localDate(end,zone.value));$<HTMLSelectElement>('day').innerHTML=[...days].sort().map(d=>`<option>${d}</option>`).join('');chooseDay();}
function chooseDay(){const [start,end]=dayRange($<HTMLSelectElement>('day').value,zone.value);$<HTMLInputElement>('start').value=localInput(start,zone.value);$<HTMLInputElement>('end').value=localInput(end,zone.value);}
function params(){const start=localToUtc($<HTMLInputElement>('start').value,zone.value),end=localToUtc($<HTMLInputElement>('end').value,zone.value);if(start>end)throw new Error('The end of the interval must be after its start.');return {start,end,seconds:Number($<HTMLSelectElement>('density').value)};}
async function render(){const generation=++renderGeneration;$<HTMLButtonElement>('export').disabled=true;$<HTMLButtonElement>('original').disabled=true;try{const r=await request({type:'reconstruct',...params()});if(generation!==renderGeneration)return;current=r;tracks.clearLayers();highlight?.remove();$('empty-map').hidden=!!r.points.length;
 for(const s of r.sections as Section[]){const line=L.polyline([[s.a.lat,s.a.lon],[s.b.lat,s.b.lon]],{color:colors[s.confidence],weight:s.confidence==='gap'?2:4,dashArray:s.confidence==='recorded'?undefined:s.confidence==='gap'?'2 9':'6 7',opacity:s.confidence==='gap'?.5:.85}).addTo(tracks);line.on('click',e=>{L.DomEvent.stopPropagation(e);selectPoint(s.a);});}
 for(const p of (r.points as Point[]).filter(p=>!p.generated).filter((_,i)=>i%Math.max(1,Math.ceil(r.originalCount/1500))===0)){L.circleMarker([p.lat,p.lon],{radius:3,color:colors.recorded,weight:1,fillOpacity:1}).addTo(tracks).bindPopup(escape(metadata(p)));}
 if(r.points.length){for(const [p,title] of [[r.points[0],'S'],[r.points.at(-1),'E']] as [Point,string][]){L.marker([p.lat,p.lon],{icon:L.divIcon({className:'endpoint',html:title,iconSize:[26,26],iconAnchor:[13,13]})}).addTo(tracks);}$('track-title').textContent=$<HTMLSelectElement>('day').value+' · '+zone.value;$('first-time').textContent=formatTime(r.start);$('last-time').textContent=formatTime(r.end);}
 $('timeline').innerHTML=(r.sections as Section[]).map((s,i)=>`<button class="${s.confidence}" data-section="${i}" style="flex-grow:${Math.max(1,s.b.time-s.a.time)}" title="${escape(s.a.source+' · '+s.confidence+' · '+formatTime(s.a.time))}" aria-label="${escape(s.a.source+' '+s.confidence+' '+formatTime(s.a.time))}"></button>`).join('');document.querySelectorAll<HTMLButtonElement>('[data-section]').forEach(b=>b.onclick=()=>selectPoint(r.sections[Number(b.dataset.section)].a));
 $('stats').innerHTML=[[`${(r.metres/1000).toFixed(2)} km`,'Approx. distance'],[r.originalCount.toLocaleString(),'Recorded points'],[r.generatedCount.toLocaleString(),'Estimated points'],[r.gaps.toLocaleString(),'Gaps']].map(([v,k])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('');
 status(r.points.length?`${sources.length} source file${sources.length===1?'':'s'} · ${[...new Set(sources.map(s=>s.format))].join(', ')} · duration ${((r.end-r.start)/3600000).toFixed(2)} hours · ${r.totalCount.toLocaleString()} output points. ${r.gaps?'Gaps are preserved as separate GPX segments.':''}`:'No GPS points in the selected interval. Choose another day.');$<HTMLButtonElement>('export').disabled=!r.points.length;$<HTMLButtonElement>('original').disabled=!r.points.length;
 }catch(e){if(generation===renderGeneration)status(e instanceof Error?e.message:'Reconstruction failed.',true);}}
async function importFiles(files:File[]){if(busy)return;if(sources.length+files.length>limits.files){status('Up to 20 files can be loaded at once.',true);return;}busy=true;$('drop').setAttribute('aria-busy','true');let errors:string[]=[];try{for(const file of files){const start=performance.now();try{const id=crypto.randomUUID();const r=await request({type:'import',file,fileId:id});sources.push({id,name:file.name,...r});telemetry('processed',r.format,performance.now()-start,file.size);telemetry('conversion_success',r.format,performance.now()-start,file.size);errors.push(...r.warnings);}catch(e){telemetry('conversion_failed','unknown',performance.now()-start,file.size);errors.push(`${file.name}: ${e instanceof Error?e.message:'Unsupported file.'}`);}}list();if(sources.length){setDays();await render();fit();}if(errors.length)status(errors.join(' '),true);}finally{busy=false;$('drop').removeAttribute('aria-busy');$<HTMLInputElement>('files').value='';}}
function fit(){if(current?.points.length)map.fitBounds(current.points.map((p:Point)=>[p.lat,p.lon]),{padding:[35,35],maxZoom:16});}
$('fit').onclick=fit;
$<HTMLInputElement>('files').onchange=e=>void importFiles([...((e.target as HTMLInputElement).files||[])]);
$('drop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$<HTMLInputElement>('files').click();}};
for(const event of ['dragenter','dragover'])$('drop').addEventListener(event,e=>{e.preventDefault();$('drop').classList.add('dragover');});$('drop').ondragleave=()=>$('drop').classList.remove('dragover');$('drop').ondrop=e=>{e.preventDefault();$('drop').classList.remove('dragover');void importFiles([...(e.dataTransfer?.files||[])]);};
$('day').onchange=()=>{chooseDay();void render().then(fit);};for(const id of ['start','end','density'])$(id).onchange=()=>void render();zone.onchange=()=>{setDays();void render();};
async function download(originalOnly=false){try{const r=await request({type:'export',...params(),originalOnly});const blob=new Blob([r.gpx],{type:'application/gpx+xml'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=$<HTMLInputElement>('start').value.slice(0,10)+'-geoconversion'+(originalOnly?'-original':'')+'.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);telemetry('gpx_export');status('Validated GPX downloaded. Load it in Lightroom Classic’s Map module → Tracklog → Load Tracklog.');}catch(e){telemetry('application_error');status(e instanceof Error?e.message:'GPX export failed.',true);}}
$('export').onclick=()=>void download();$('original').onclick=()=>void download(true);
function resetView(){renderGeneration++;current=null;tracks.clearLayers();highlight?.remove();$('empty-map').hidden=false;$('timeline').innerHTML='';$('track-title').textContent='Your route starts here';$('metadata').textContent='Add a location file to begin.';for(const id of ['export','original'])$<HTMLButtonElement>(id).disabled=true;status('Sources cleared from browser memory.');}
$('clear').onclick=async()=>{if(busy)return;await request({type:'clear'});sources.length=0;list();resetView();};
$('help').onclick=()=>{$('guide').hidden=!$('guide').hidden;if(!$('guide').hidden)$('guide').scrollIntoView({behavior:'smooth'});};
$('demo').onclick=()=>{const points=Array.from({length:16},(_,i)=>({point:`geo:${35.6812+i*.0008},${139.7671+i*.0007}`,time:new Date(Date.UTC(2027,2,18,2,0,i*60)).toISOString()}));points.push({point:'geo:35.7000,139.7900',time:'2027-03-18T03:00:00Z'});void importFiles([new File([JSON.stringify({semanticSegments:[{startTime:'2027-03-18T02:00:00Z',endTime:'2027-03-18T03:00:00Z',timelinePath:points}]})],'sample-timeline.json',{type:'application/json'})]);};
window.addEventListener('pagehide',()=>{worker.terminate();sources.length=0;current=null;});window.addEventListener('error',()=>telemetry('application_error'));
